# Site Settings
title: Welcome | Vignesh A K
description: Exploring the intersection of Neuroscience and Artificial Intelligence.

url: "https://vignesh0906.github.io"
baseurl: ""

# Hydejack 9.2.1
remote_theme: hydecorp/hydejack@v9.2.1

# Author
author:
  name: Vignesh A K
  email: vignesh090601@gmail.com
  social:
    github: vignesh0906

# Hydejack settings
accent_image: /assets/img/sidebar-bg.jpg

menu:
  - title: Welcome
    url: /
  - title: About
    url: /about/
  - title: CV
    url: url: /assets/Vignesh_AK_Resume.pdf
  - title: Research
    url: /Research/
  - title: Publications
    url: /Publications/
  - title: Open source projects
    url: /Open source projects/
  - title: Community Involvement
    url: /Community Involvement/
  - title: Contact
    url: /Contact/

# Plugins required for GitHub Pages / Hydejack
plugins:
  - jekyll-include-cache

# Build settings
markdown: kramdown
permalink: /:categories/:year-:month-:day-:title/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
